#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
osa1 Arsiv Duzenleme Scripti! icin nautilus scripti!

Nautilus ile secilen dosyalari alip, gerekli karakterleri
degistirerek uyumlu hale getirir, daha sonra secili
klasorleri osa1'e gonderir.

Bu script duzenleme isini farkli bir klasorde yapar,
buzeniniz herhangi bir sekilde bozulmaz!!1
"""
import os, sys
from osa1 import osa1

yer = os.environ['NAUTILUS_SCRIPT_SELECTED_FILE_PATHS'].split('\n')

for s in yer:
    hedef = '%s/DUZENLI' % s
    osa1.duzenle(s, hedef)
