#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
osa1 Arsiv Duzenleme Scripti! icin nautilus scripti!

Nautilus ile secilen dosyalari alip, gerekli karakterleri
degistirerek uyumlu hale getirir, daha sonra secili
klasorleri osa1'e gonderir.

Bu script duzenleme isini ayni klasorde yapar, duzeniniz
bozulabilir!!1
"""
import os, sys
from osa1 import osa1

sys.stderr = open('/home/osa1/Desktop/stderr.txt', 'w')

yer = os.environ['NAUTILUS_SCRIPT_SELECTED_FILE_PATHS'].split('\n')

for s in yer:
    osa1.duzenle(s, s, yontem=osa1.yurut)
